spring:
  datasource:
    druid:
      url: jdbc:mysql://host.lvm2:3306/news_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root*123
      stat-view-servlet:
        login-username: admin
        login-password: admin
